version: "3"
services:
  web:
    build: ./nginx
    environment:
      - PHP_SITES=apiv1 apiv2 apiv3
      - STATIC_SITES=cc2
    volumes:
      - ./applications:/code
#      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf #Uncomment this line during development so we don't have to rebuild for every change
#      - ./nginx/docker-entrypoint.sh:/docker-entrypoint.sh #Uncomment this line during development so we don't have to rebuild for every change
#      - ./nginx/templates:/etc/nginx/site-templates #Uncomment this line during development so we don't have to rebuild for every change
    ports:
      - 420:80
    links:
      - php-7-3-fpm-alpine

  php-7-3-fpm-alpine:
    build: ./php-fpm
    volumes:
      - ./applications:/code
    working_dir: /code
