version: "3"
services:
  web:
    image: nginx:latest
    ports:
      - 420:80
    environment:
      - APP_TLD=gmorales.local
      - PHP_SITES=apiv1 apiv2 apiv3
      - STATIC_SITES=cc2
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/docker-entrypoint.sh:/docker-entrypoint.sh
      - ./nginx/templates:/etc/nginx/site-templates
      - ./applications:/code
    command: []
    entrypoint: ["/bin/bash", "-c", "/docker-entrypoint.sh"]
    links:
      - php-7-3-fpm-alpine

  php-7-3-fpm-alpine:
    image: php:7.3-fpm-alpine
    volumes:
      - ./applications:/code
    working_dir: /code
